config/routes.rb
Lingo::Application.routes.draw do
  
get "/" => "Words#index"

get "/words" => "Words#index", :as => :words
get "/words/new" => "Words#new", :as => :new_word
get "/words/flagged" => "Words#flagged", :as => :flagged_words


get "/words/:id" => "Words#show", :as => :show_word



post "/words/" => "Words#create", :as => :words

get "/words/vote_up/:id" => "Words#vote_up", :as => :vote_up
get "/words/delete/:id" => "Words#delete", :as => :delete

get "/words/flag/:id" => "Words#flag", :as => :flag
get "/words/unflag/:id" => "Words#unflag", :as => :unflag


end

app/models/word.rb
class Word < ActiveRecord::Base
  attr_accessible :def, :flagged, :term, :vote
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/words_controller.rb
class WordsController < ApplicationController
  
  def index
  @words = Word.find(:all, :order => "vote DESC", :conditions => ['flagged = ?', false])
  
  end
  
  def show
    @word = Word.find(params[:id])
  end
  
  def flagged
    @words = Word.find(:all, :order => "vote DESC", :conditions => ['flagged = ?', true])
    
  end
  
  def delete
    w = Word.find(params[:id])
    w.destroy
    redirect_to "/words/flagged"
    
  end
  
  def new
    @word = Word.new    
  end
  
  def create
    w = Word.new
    w.term = params[:word][:term]
    w.def = params[:word][:def]
    w.vote = 0
    w.flagged = false
    w.save
    
    redirect_to "/words"
  end
  
  def vote_up
    w = Word.find(params[:id])
    w.vote += 1 
    w.save
    
    redirect_to "/words"
  end
  
  def flag
    
    w = Word.find(params[:id])
    w.flagged = true 
    w.save
    
    redirect_to "/words"
  end
  
  def unflag
    w = Word.find(params[:id])
    w.flagged = false 
    w.save
    
    redirect_to "/words/flagged"
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Lingo</title>

  <link href='http://fonts.googleapis.com/css?family=Rokkitt:400,700' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Salsa' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Francois+One' rel='stylesheet' type='text/css'>



  <%= stylesheet_link_tag "application", "tipsy", :media => "all" %>

  <%= javascript_include_tag "jquery", "jquery.tipsy", "application" %>
  <%= csrf_meta_tags %>

  <script type='text/javascript'>
   $(function() {
	$('a.tooltip').tipsy({fade: true});
   });

  </script>

</head>
<body>

<%= yield %>

</body>
</html>

app/views/words/flagged.html.erb
<h1><%= link_to "CORPORATE WANK", words_path %></h1>
<h2>Flagged Words</h2>

<table class="main">
	<% @words.each do |word| %>
	<tr>
			<td class="record"><%= link_to image_tag("delete.png"), "/words/delete/"+word.id.to_s %></td>
			<td class ="record">
				<ul class = "term-def-pair">
					<li id = "term"><%=word.term  %></li>
					<li id = "definition"><%=word.def  %></li>
					<li align='right'><%= link_to image_tag("flag.png"), "/words/unflag/"+word.id.to_s, :class => 'flag' %></li>
				</ul>
	</tr>
	<% end %>
	
</table>

app/views/words/index.html.erb
<h1>CORPORATE WANK</h1>
<h2>A handy glossary for new players</h2>

<div class = "nav"><%= link_to "Add Term", new_word_path, :class => 'button' %></div>

<table class="main">
	<% @words.each do |word| %>
	<tr>
			<td class="record" id="flag-etc">
				<%= link_to image_tag("thumb-white.png"), "/words/vote_up/"+word.id.to_s, :class => "tooltip", :title => "VOTE UP!" %>
			</td>
			
			
			<td id = "votes" class="record"><%= word.vote %></td>
			<td class ="record">
				<ul class = "term-def-pair">
					<li id = "term"><%=word.term  %></li>
					<li id = "definition"><%=word.def  %></li>
				</ul>
			</td>
			<td class="record" id = "flag-etc">
				<%= link_to image_tag("flag.png"), "/words/flag/"+word.id.to_s, :class => 'tooltip flag', :title => "Report Abuse" %>
			<br>
			<%= link_to image_tag("twitter-bird-dark-bgs-small.png"), "http://twitter.com/home?status= Corporate dictionary: #{word.term} http://fathomless-meadow-2743.herokuapp.com/words/"+word.id.to_s, :class => "tooltip", :title => "Share on Twitter" %>
			</td>
	</tr>
	<% end %>
	
</table>

app/views/words/new.html.erb
<h1></h1>

<div id="form">
<h2>Add a new Term</h2>

<div id="new-form">
	<%= form_for @word do |f|  %>
	<ul>
			<li>Word/Phrase<br><%= f.text_field :term  %></li>
			<li>Definition<br><%= f.text_area :def, rows:5  %></li>
			<li><%= f.submit 'Add word', :class => 'btn btn-success'%></li>

	</ul>
	<% end %>
</div>

app/views/words/show.html.erb
<h1>CORPORATE WANK</h1>
<h2>A handy glossary for new players</h2>

<table class="main">
	<tr>
			<td class="record"><%= link_to image_tag("thumb-white.png"), "/words/vote_up/"+@word.id.to_s %></td>
			<td id = "votes" class="record"><%= @word.vote %></td>
			<td class ="record">
				<ul class = "term-def-pair">
					<li id = "term"><%=@word.term  %></li>
					<li id = "definition"><%=@word.def  %></li>
				</ul>
			</td>
			<td><td class="record"><%= link_to image_tag("flag.png"), "/words/flag/"+@word.id.to_s, :class => 'flag' %></td>
			</td>
	</tr>
	
</table>